# Generated by Django 4.0.4 on 2022-04-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_text_en_post_text_ru_post_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_ru',
        ),
    ]
