# Generated by Django 4.0.4 on 2022-05-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
